import { utilityTheme } from '@redesign-system/theme'

export const ignoreAttributes = [
  ...Object.keys(utilityTheme({})),
  'childrenCss',
  'childrenProps',
  'css',
  'theme',
  'as',
  'stacked',
  '__ignore',
  'pill',
  'invalid',
  'stretch',
  'hover',
  'condensed',
  'dispatch',
  'appearance',
  'element',
  'smallAppBar',
  'flip',
  'justify',
  'opened',
  'columns',
  'cover',
  'parallax',
  'repeat',
  'active',
]
